version: '3'

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/rofontai/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/rofontai/data/mariadb'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    networks:
      - inception
    ports:
      - "443:443"
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: on-failure
    volumes:
      - wordpress:/var/www/wordpress

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    networks:
      - inception
    ports:
      - "3306:3306"
    env_file:
      - .env
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    networks:
      - inception
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: on-failure
    volumes:
      - wordpress:/var/www/wordpress


